# Generated by Django 4.2.6 on 2023-10-28 09:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_restframework_gis_tests", "0003_schema_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boxedlocation",
            name="geometry",
        ),
        migrations.RemoveField(
            model_name="boxedlocation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="boxedlocation",
            name="name",
        ),
        migrations.RemoveField(
            model_name="boxedlocation",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="boxedlocation",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="locatedfile",
            name="geometry",
        ),
        migrations.RemoveField(
            model_name="locatedfile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="locatedfile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="locatedfile",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="locatedfile",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="boxedlocation",
            name="location_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="django_restframework_gis_tests.location",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locatedfile",
            name="location_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="django_restframework_gis_tests.location",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
